### ISSUE TITLE
Cannot compile class after compile error

### ISSUE THREAD

**Issue by ikabiljo** [OpenHFT/Java-Runtime-Compiler#12]
After trying to load class that has compile error, CachedCompiler cannot compile anything successfully any more:

    String className = "MyClass";
    String javaCode = "public class MyClass {}";

    try {
      CompilerUtils.CACHED_COMPILER.loadFromJava("z" + className, " some compile error " + javaCode);
    } catch (Exception ex) {
      ex.printStackTrace();
    }

    // This should work, but throws an exception:
    CompilerUtils.CACHED_COMPILER.loadFromJava(className, javaCode);

**Comment by leventov** [comment]
Could you please test with the latest snapshot? By specifying in pom:

```xml
<repository>
    <id>Snapshot Repository</id>
    <name>Snapshot Repository</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

...

<dependency>
  <groupId>net.openhft</groupId>
  <artifactId>compiler</artifactId>
  <version>2.2.4-SNAPSHOT</version>
</dependency>
```

Or downloading the latest master tree and building `mvn install` from command line, then specifying compiler dependency version to `2.2.4-SNAPSHOT`

**Comment by ikabiljo** [comment]
Thanks, that works both for the simple repro, and the actual code that was failing.

**Comment by sudiptoimpmail** [comment]
I have this code

aClass = CompilerUtils.CACHED_COMPILER.loadFromJava(cl, className, javaCode);
ISandcCalculatedDataPointExecute runner = (ISandcCalculatedDataPointExecute) aClass.newInstance();
ans = runner.execute(keyVal);

but I am getting can not find symbol even when ISandcCalculatedDataPointExecute is in same package in war. This is working eclipse but not in weblogic.

**Comment by terrancesnyder** [comment]
+1 any chance we can have a new build here to mvn central instead of snapshot or a least a locked down version we can reference like "rc-01"?

**Comment by leventov** [comment]
@terrancesnyder doesn't `net.openhft:compiler:2.2.4` released on Maven?

**Comment by renatoathaydes** [comment]
I am using version `2.2.4` and it seems this problem is not resolved.

It looks like a new class can be compiled after an error, as no error is thrown, but the class does not seem to be compiled at all.

Here's [my unit test](https://github.com/renatoathaydes/osgiaas/blob/master/lang/osgiaas-javac/src/test/java/com/athaydes/osgiaas/javac/JavacServiceTest.java#L99) that is currently failing:

```java
@Test
public void canDefineClassAfterCompilerError() throws Exception {
    String errorDef = "clazz Bad{ public String get() {return \"bad\";}}";
    String classDef = "class Good{ public String get() {return \"good\";}}";

    // use our own classloader to be more realistic
    ClassLoader classLoader = new URLClassLoader( new URL[]{ } );

    // compiler error
    try {
        javacService.compileJavaSnippet(
                JavaSnippet.Builder.withCode( "return null;" )
                        .withClassDefinitions( Collections.singleton( errorDef ) ),
                classLoader );
        fail( "Should not have compiled class successfully" );
    } catch ( Throwable t ) {
        // ignore
    }

    // compile good class
    javacService.compileJavaSnippet(
            JavaSnippet.Builder.withCode( "return null;" )
                    .withClassDefinitions( Collections.singleton( classDef ) ),
            classLoader );

    // use good class
    Callable script = javacService.compileJavaSnippet(
            JavaSnippet.Builder.withCode( "return new Good().get();" ) );

    Object result = script.call();

    assertEquals( "good", result );
}
```

Error:

```
/JavaSnippet3.java:4: error: cannot find symbol
return new Good().get();
           ^
  symbol:   class Good
  location: class JavaSnippet3
```

I am using a [thin wrapper](https://github.com/renatoathaydes/osgiaas/blob/master/lang/osgiaas-javac/src/main/java/com/athaydes/osgiaas/javac/JavacService.java) around your library, but I am pretty sure that the problem is not on my wrapper as it just delegates to 

`CompilerUtils.CACHED_COMPILER.loadFromJava( classLoader, qualifiedName, code );`

Not setting the classLoader makes no difference. If you comment out the try/catch that causes a compilation error, the test passes.

If the code using the good class is run together with the compilation of the good class, it does work... It just seems to not remember the definition of the class in subsequent calls.

So, even though trying to refer to the `Good` class directly fails with `error: cannot find symbol [Good]`, doing `Class.forName("Good")` succeeds.

**Comment by peter-lawrey** [comment]
I plan to do a round of releases on Monday.
