### ISSUE TITLE
ClassLoader provided to loadFromJava() is not used to when actually compiling a class

### ISSUE THREAD

**Issue by renatoathaydes** [OpenHFT/Java-Runtime-Compiler#19]
Classes loaded by the classLoader provided to the `CachedCompiler` are  not visible to the class being compiled.

For example, in OSGi, if you have a class `A` in a bundle, then call `CachedCompiler.loadFromJava()` using that bundle's class loader to compile a class which refers to `A`, an error occurs as `A` is not found.

It seems the problem is that the `JavaFileManager` does not use the classLoader provided to `loadFromJava()`.

I will try to fix this and make a pull request in the next couple of days or hours.

**Comment by peter-lawrey** [comment]
Thank you. I will hold off the a release for this update.

**Comment by renatoathaydes** [comment]
I've looked into this. It's a hard one...

There's a [StackOverflow question](http://stackoverflow.com/questions/5819376/java-compiler-api-classloader) about this exact problem with useful answers, but anyway to make this work would be a major rewrite, I think... so don't wait for this, not sure I will have time to do this.

**Comment by leventov** [comment]
Probably I have already addressed this issue here: https://github.com/OpenHFT/Chronicle-Values/tree/master/src/main/java/net/openhft/chronicle/values

(Chronicle Values used to depend on Java Runtime Compiler, then I copied JRC sources to Values source tree and addressed class loading issues; you could trace it in Chronicle Values commit history).

However, since this problem floated: http://blog.siteos.de/java/javaee/chroniclemap/2016/05/16/How-To-Use-ChronicleMap-With-JavaEE.html, I wasn't able to resolve the problem completely.

**Comment by renatoathaydes** [comment]
I asked on StackOverflow, but after a few days battling with this, I figured it out and answered the question myself!

http://stackoverflow.com/questions/38467876/how-to-get-the-javacompiler-to-use-a-provided-classloader-to-find-a-class

To implement the solution in this project will be hard, I think, but feel free to get some of the code from my implementation of the compiler if you want.

**Comment by victornoel** [comment]
Hey people, I'm facing the same issue and I'm not sure I understand everything, but couldn't we use the solution provided here https://stackoverflow.com/a/1564025 to inject the right classpath (as long as it's available on disk…) into the `CachedCompiler`? This would be a solution in user code, not in this project I think…

Or is that not enough?
